name: Running tests

on: 
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running tests
        run: |
          cd qscache/
          pip install -r requirements.txt
          python3 manage.py test
